//ANSHUL TANWAR 486 1/09/2023
// PARTICLE IN A BOX
clear()
clc()
clf()
n=linspace(0,1,100)
x=zeros(length(n),length(n))
h=n(2)-n(1);
for i=1:length(n)-1
    x(i,i)=-2
    x(i,i+1)=1
    x(i+1,i)=1
end
x=x*(1/(h*h))
x=x*((-1973*1973)/(2*0.511*10^6))  //eV

//disp(x)

[a,b]=spec(x)

//disp("eigenfunction= ",a(:,1))
//disp("eigenvalues = ",diag(b))
for i=1:6
    subplot(4,3,i)
    plot(n,a(:,i+1)','r')
    xgrid
    xlabel("x(in Angstrom)------->")
    ylabel("⨚ ------->")
     legend(["wave function"])
end

//plotting probablity density

for i=1:6
    subplot(4,3,i)
    plot(n,(a(:,i+1)')^2,'g')// since prob = |⨚|^2
    xgrid
    xlabel("x(in Angstrom)------->")
    ylabel("|⨚|^2 ------->")
    legend(["probablity density"])
end

// energy levels
disp("energy levels = ")
for n=1:6
    E=(((n^2)*(1973*2*%pi)^2)/(8*0.511*10^6))
    disp(E)
end

